### PR TITLE
Remove autopublish from app

### PR DESCRIPTION
**Pull request by mikegazdag**
* Fixed the Lines not working by publishing them on the server, and then setting up a subscriber for the client.

### CODE REVIEW

**Comment by stephenhammond** [comment]
I DO NOT APPROVE OF THIS PULL REQUEST.  Code is NOT ready for turning off autopublish.

**Comment by mikegazdag** [comment]
@stephenhammond something broke for you? All the features were working for me...

**Comment by stephenhammond** [comment]
With multiple log ins... When a user isn't logged in, other users and
presenters weren't displaying properly.

- Captain User System

**Comment by mikegazdag** [comment]
@stephenhammond ;_;7 :us:

**Comment by stephenhammond** [comment]
I now approve now. changed users.js to subscribe to all users collection.

**Pull request merged**
