### PR TITLE
App ui refresh

### PR DESCRIPTION
**Pull request by mikegazdag**
Tweaks! @stephenhammond @dvkry @nuen

### CODE REVIEW

**Comment by stephenhammond** [comment]
I love pull requests.

**Comment by stephenhammond** [comment]
@mikegazdag I'm going to leave this one for now to allow for the tweaks we discussed....

in app.js 

  if (editorPort < 0) {
    editorPort = 600;
  }
  else {
    $('#editor').css("height", editorPort  + "px");
  }

**Comment by mikegazdag** [comment]
Thanks @stephenhammond

**Comment by stephenhammond** [comment]
- light coloured vertical bar on blackboard needs to be removed
- bug allows scrolling to right

**Pull request merged**
